version: "3.9"

services:
    books:
        build: .
        environment: 
            APP: books
            PORT: 4000
        ports:
            - "4000:4000"
    gateway:
        build: .
        ports:
            - "3000:3000"
        links:
            - books