version: "3.9"

services:
    books:
        build: .
        environment: 
            APP: books
            PORT: "4000"
        container_name: books
        ports:
            - "4000:4000"
            - "5000:5000"
    gateaway:
        build: .
        container_name: gateaway
        ports:
            - "3000:3000"