version: "3.9"

services:
    books:
        build: .
        environment: 
            APP: books
        container_name: books
        ports:
            - "4000:4000"
            - "5000:5000"
    users:
        build: .
        environment: 
            APP: users
        container_name: users
        ports:
            - "4001:4000"
            - "5001:5000"
    gateaway:
        build: .
        container_name: gateaway
        ports:
            - "3000:3000"