version: "3.9"

services:
    gateaway:
        build: .
        container_name: gateaway
        ports:
            - "3000:3000"
    books:
        build: .
        environment: 
            APP: books
        container_name: books
    users:
        build: .
        environment: 
            APP: users
        container_name: users